USE [StackOverflow2010]
GO

ALTER DATABASE StackOverflow2010
ADD FILEGROUP POSTS;  
GO  
ALTER DATABASE StackOverflow2010
ADD FILE   
(  
    NAME = PostsFile1,  
    FILENAME = 'D:\SQLServer\MSSQL14.MSSQLSERVER\MSSQL\DATA\StackOverflow2010_POSTS_F1.ndf',  
    SIZE = 4096MB,  
    FILEGROWTH = 256MB 
)
TO FILEGROUP POSTS;  
GO

